title: AUAAS
description: Official website of the UAV Student Club.
baseurl: "/auaas-website" # Leave empty for root
url: "https://auaas.github.io"

theme: null # No default theme
plugins:
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
